# Generated by Django 3.0.6 on 2020-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(default='this is super'),
        ),
    ]
