# Generated by Django 3.0.6 on 2020-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200606_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('status', models.CharField(default='succesful', max_length=100)),
            ],
        ),
    ]
