# Generated by Django 3.0.6 on 2020-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='request1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='unsuccesful', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='request',
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='unsuccesful', max_length=100),
        ),
    ]
