# Generated by Django 3.0.6 on 2020-06-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200606_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request1',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
